version: '2'
services:
    adonline-app:
        image: adonline
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://adonline-mysql:3306/adonline?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    adonline-mysql:
        extends:
            file: mysql.yml
            service: adonline-mysql
